version: '3.8'

services:

  desadb:
    image: postgres
    restart: always
    environment: 
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=desa
      - POSTGRES_PASSWORD=desa
      - POSTGRES_DB=desa
    volumes:
      - ../database/desa:/bitnami/postgresql
  
  keycloakdb:
    image: postgres
    restart: always
    environment: 
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak
    volumes:
      - ../database/keycloak:/bitnami/postgresql

  pgadmin:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "desa"
    ports:
      - "8080:80"
    depends_on: 
      - desadb
      - keycloakdb

  keycloak:
    image: docker.io/bitnami/keycloak:12-debian-10
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_ADMIN_USER=user
      - KEYCLOAK_ADMIN_PASSWORD=user
      - KEYCLOAK_DATABASE_HOST=keycloakdb
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=keycloak
      - KEYCLOAK_DATABASE_PASSWORD=keycloak
    depends_on:
      - keycloakdb
    volumes:
      - ./mynewtheme:/opt/bitnami/keycloak/themes/mynewtheme

  backend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: desaapp
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - 5000:5000
    depends_on:
      - desadb
    volumes:
      - ../backend/:/code

  