version: '3.8'

services:

  db:
    image: mysql
    container_name: desadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ../database/mysql/dump:/dump
    environment:
      MYSQL_ROOT_PASSWORD: desa
      MYSQL_USER: desa
      MYSQL_PASSWORD: desa
      MYSQL_DATABASE: desa
    healthcheck:
      test: ["CMD", "phpmyadmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin
    container_name: desaphpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOSTS: db
      PMA_USER: root
      PMA_PASSWORD: desa

  backend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: desaapp
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - 5000:5000
    depends_on:
      - db
    volumes:
      - ../backend/:/code

  