#!/bin/bash

# Se exorta los dumps
#docker exec -d desadb /bin/bash -c 'mysqldump desa -uroot -pdesa  > /dump/dump.sql'
docker exec -t desadb pg_dumpall -c -U postgres > ../database/desa/dump.sql
docker exec -t keycloakdb pg_dumpall -c -U postgres > ../database/keycloak/dump.sql

